CREATE DATABASE photoapp;
USE photoapp;

CREATE TABLE `user` (
  `USERNAME` varchar(50) NOT NULL,
  `EMAILID` varchar(95) DEFAULT NULL,
  `PASSWORD` varchar(45) DEFAULT NULL,
  `TIMESTAMP` datetime DEFAULT NULL,
  PRIMARY KEY (`USERNAME`),
  UNIQUE KEY `USERNAME_UNIQUE` (`USERNAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `posts` (
  `POSTNAME` varchar(50) NOT NULL,
  `USERNAME` varchar(45) DEFAULT NULL,
  `COMMENTS` varchar(145) DEFAULT NULL,
  `TIMESTAMP` datetime DEFAULT NULL,
  `IMAGENAME` varchar(45) NOT NULL,
  PRIMARY KEY (`POSTNAME`),
  KEY `USERNAME_idx` (`USERNAME`),
  CONSTRAINT `USERNAME` FOREIGN KEY (`USERNAME`) REFERENCES `user` (`USERNAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `comments` (
  `POSTNAME` varchar(30) DEFAULT NULL,
  `USERNAME` varchar(30) DEFAULT NULL,
  `COMMENTS` varchar(500) DEFAULT NULL,
  `TIMESTAMP` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

